"use client";
import Link from "next/link";
import { Check, MapPin, CreditCard, Truck } from "lucide-react";
import { money } from "@/components/commerce/data";
import { useState } from "react";

export function CheckoutForm({ guest = false }: { guest?: boolean }) {
 const [method,setMethod]=useState("upi"); const [placed,setPlaced]=useState(false);
 if(placed) return <div className="mx-auto max-w-2xl px-6"><div className="rounded-2xl border border-gray-200 bg-white p-10 text-center shadow-sm"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-green-50 text-green-600"><Check/></div><h2 className="mt-5 text-2xl font-semibold">Order placed successfully</h2><p className="mt-2 text-sm text-gray-500">Your order <span className="font-medium text-gray-900">#KO-10502</span> has been created.</p><Link href="/orders" className="mt-6 inline-flex rounded-lg bg-[#5b4ef9] px-5 py-3 text-sm font-medium text-white">View Orders</Link></div></div>;
 return <div className="mx-auto grid max-w-7xl gap-6 px-6 lg:grid-cols-[1fr_380px]">
   <div className="space-y-5">
    {guest && <section className="rounded-2xl border border-gray-200 bg-white p-5"><h2 className="font-semibold">Contact details</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm text-gray-600">Full name<input className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2.5 outline-none focus:border-[#5b4ef9]" placeholder="Your name"/></label><label className="text-sm text-gray-600">Mobile number<input className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2.5 outline-none focus:border-[#5b4ef9]" placeholder="+91 98765 43210"/></label><label className="text-sm text-gray-600 sm:col-span-2">Email address<input className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2.5 outline-none focus:border-[#5b4ef9]" placeholder="you@example.com"/></label></div></section>}
    <section className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex items-center gap-3"><span className="rounded-lg bg-[#5b4ef9]/10 p-2 text-[#5b4ef9]"><MapPin className="h-5 w-5"/></span><div><h2 className="font-semibold">Delivery address</h2><p className="text-sm text-gray-500">Where should we deliver your order?</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><input className="rounded-lg border border-gray-200 px-3 py-2.5" placeholder="Full name"/><input className="rounded-lg border border-gray-200 px-3 py-2.5" placeholder="Phone number"/><input className="rounded-lg border border-gray-200 px-3 py-2.5 sm:col-span-2" placeholder="Address line"/><input className="rounded-lg border border-gray-200 px-3 py-2.5" placeholder="City"/><input className="rounded-lg border border-gray-200 px-3 py-2.5" placeholder="PIN code"/></div></section>
    <section className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex items-center gap-3"><span className="rounded-lg bg-[#5b4ef9]/10 p-2 text-[#5b4ef9]"><CreditCard className="h-5 w-5"/></span><div><h2 className="font-semibold">Payment method</h2><p className="text-sm text-gray-500">Choose how you want to pay.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["upi","UPI"],["card","Card"],["cod","Cash on Delivery"]].map(([id,label])=><button key={id} onClick={()=>setMethod(id)} className={`rounded-xl border p-4 text-left text-sm ${method===id?"border-[#5b4ef9] bg-[#5b4ef9]/5":"border-gray-200"}`}><p className="font-medium">{label}</p><p className="mt-1 text-xs text-gray-500">{id==="cod"?"Pay at delivery":"Secure payment"}</p></button>)}</div></section>
   </div>
   <aside className="h-fit rounded-2xl border border-gray-200 bg-white p-5 lg:sticky lg:top-28"><h2 className="font-semibold">Order summary</h2><div className="mt-5 space-y-4"><div className="flex justify-between text-sm text-gray-600"><span>Premium Cotton Shirt × 2</span><span>{money(2598)}</span></div><div className="flex justify-between text-sm text-gray-600"><span>Everyday Sneakers</span><span>{money(2499)}</span></div><div className="border-t border-gray-100 pt-4"><div className="flex justify-between text-sm text-gray-600"><span>Subtotal</span><span>{money(5097)}</span></div><div className="mt-2 flex justify-between text-sm text-gray-600"><span>Shipping</span><span className="text-green-600">Free</span></div><div className="mt-4 flex justify-between font-semibold"><span>Total</span><span>{money(5097)}</span></div></div></div><button onClick={()=>setPlaced(true)} className="mt-6 w-full rounded-lg bg-[#5b4ef9] px-5 py-3 text-sm font-medium text-white hover:bg-[#4a3ee0]">Place Order</button><div className="mt-4 flex gap-2 text-xs text-gray-500"><Truck className="h-4 w-4 shrink-0"/>Estimated delivery in 3–5 business days.</div></aside>
 </div>;
}
